### ISSUE TITLE
When a group is muted, Franz still show the notification

### ISSUE THREAD

**Issue by ms-lemos** [meetfranz/recipe-whatsapp#1]
I have some muted contacts/groups, but on Franz it keeps showing the notification that I have an unread message, even though the group is set to hide notifications.

**Expected Behavior**
It shouldn't show the notification as the group is configured to not show.

**Current Behavior**
It shows the notification that I have an unread message.

**Possible Solution**
Check if the group is configured to hide notifications.

**Steps to Reproduce (for bugs)**
1. Log in to whatsapp
2. Mute a group and configure it to hide notifications
3. Receive a message on that group
4. You'll see that the notifications are shown in Franz

**Context**
Well, I don't want to be bothered by these groups.

**Your Environment**
Franz Version used: 5.0.0-beta.10
Operating System and version: Windows 10 - Build 1511

**Comment by GustavoKatel** [comment]
I found the problem. I can work on that later.
