### ISSUE TITLE
Not running in fullscreen anymore

### ISSUE THREAD

**Issue by rojosinalma** [meetfranz/recipe-whatsapp#12]
For a couple of days now, the whatsapp web service is not running using the whole screen like it used to be. I need to zoom in a couple of times to make it look like it's using the whole window, but having it zoomed it like that is kinda weird.

Did something change either in this recipe or whatsapp web? Anybody knows what I can do to fix it?

**Comment by rojosinalma** [comment]
ping @adlk

**Comment by rojosinalma** [comment]
I found that changing the injected CSS for this fixes the issue:

```
.h70RQ.two {
    width: 100% !important;
    height: 100% !important;
    top: 0 !important;
}
```

**Comment by Letrab** [comment]
Adding this to `user.css` works for me (go to Settings of Whatsapp and scroll down, to open user.css)

```
.two {
    width: 100vw !important;
}

```
